version: '3.1'
networks:
    sanguebom:
        driver: bridge
services:
    database:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: "postgres"
            POSTGRES_DB: sanguebom
        ports:
            - "3301:5432"
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        networks:
            - sanguebom
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "sanguebom@localhost.com"
            PGADMIN_DEFAULT_PASSWORD: "sanguebom"
        ports:
            - "16543:80"
        depends_on:
            - database
        networks:
            - sanguebom
volumes:
    database:
